### ISSUE TITLE
Config error with 0.9.43

### ISSUE THREAD

**Issue by electricmonk** [mgee/hammerspoon-config#1]
Hi there,
I just forked your config, trying to get it to work with Hammerspoon 0.9.43.

Getting this error upon loading config:

```
10:18:43   [hotkey] Enabled hotkey ⌃⌥UP
           [hotkey] Enabled hotkey ⌃⌥DOWN
           [hotkey] Enabled hotkey ⌃⌥LEFT
           [hotkey] Enabled hotkey ⌃⌥RIGHT
           [hotkey] Enabled hotkey ⌃⌥SPACE
           [hotkey] Enabled hotkey ⌃⌥1
           [hotkey] Enabled hotkey ⌃⌥2
...oon.app/Contents/Resources/extensions/hs/hotkey/init.lua:325: Invalid key: ^
stack traceback:
    [C]: in function 'error'
    ...oon.app/Contents/Resources/extensions/hs/hotkey/init.lua:23: in upvalue 'getKeycode'
    ...oon.app/Contents/Resources/extensions/hs/hotkey/init.lua:176: in function 'hs.hotkey.new'
    ...oon.app/Contents/Resources/extensions/hs/hotkey/init.lua:325: in function 'hs.hotkey.bind'
    /Users/shaiyallin/.hammerspoon/init.lua:105: in main chunk
    [C]: in function 'xpcall'
    ...poon/0.9.43/Hammerspoon.app/Contents/Resources/setup.lua:270: in main chunk
stack traceback:
    ...poon/0.9.43/Hammerspoon.app/Contents/Resources/setup.lua:271: in main chunk
10:18:43 Warn: [wfilter] Hammerspoon (33137) is not registered yet
```

What am I missing? bear in mind that I'm completely new to Hammerspoon.

Thanks!

**Comment by mengelbrecht** [comment]
Hammerspoon complains that the `^` hotkey could not be bound.
It seems like the issue  is similar to [this one](https://github.com/Hammerspoon/hammerspoon/issues/616).
The cause could be a special keyboard layout or maybe the hotkey is already bound by the system or another application...

Try executing this line in the Hammerspoon console (accessible via the menu):

```
hs.eventtap.new({hs.eventtap.event.types.keyUp},function(e)print(hs.inspect(e:getRawEventData()))end):start()
```

Then press the `^` key. It should show up some `NSEventData` in the Hammerspoon console.
What is the `keyCode` which is printed in the console? For me it displays `10` as key code for `^`.

You can then use the key code to bind the hotkey. In case the key code is 10 change `hs.hotkey.bind(mash, '^', function() ...` to `hs.hotkey.bind(mash, 10, function() ...`

If this does not work, is the `^` key already bound by another application in your system?

**Comment by electricmonk** [comment]
Interestingly enough, I get no output for none of the `cmd`, `option` or `ctrl` keys.
My keyboard layout is ISO European.

**Comment by mengelbrecht** [comment]
I also did not get any output for the `cmd`, `option` and `ctrl` keys. Did you get some output for the `^` key?

**Comment by electricmonk** [comment]
Hmmm. Maybe I’m missing something, but doesn’t `^` mean `ctrl`? 

-- 
http://www.shaiyallin.com

On November 25, 2015 at 8:38:42 PM, Markus Engelbrecht (notifications@github.com) wrote:

I also did not get any output for the cmd, option and ctrl keys. Did you get some output for the ^ key?

**Comment by mengelbrecht** [comment]
Ah this may be the problem. The `^` key has the same symbol as the `ctrl` key but what is meant in this context is the [caret key](https://en.wikipedia.org/wiki/Caret). For my keyboard it is located directly to the left of the `1` key. However, this may vary on your keyboard.
